twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    # Injection de la variable globale "helloworld"
    #   /config/services.yaml 
    #   parameters:
    #       helloworld: <content>
    globals:
        helloworld: '%helloworld%'
        GLOBAL_NUMBER: '%GLOBAL_NUMBER%'
    
    # Activate Bootstrap Template
    form_themes: ['bootstrap_4_layout.html.twig']