# vich_uploader:
#     db_driver: orm

#     mappings:
#         advert_image:
#             uri_prefix: /uploads/adverts/images/
#             upload_destination: '%kernel.project_dir%/public/uploads/adverts/images'